default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: cook_book_api_development

test:
  <<: *default
  database: cook_book_api_test

production: &default
  adapter: postgresql
  database: cook_book_api_production
  host: <%= ENV["POSTGRES_HOST"] %>
  port: 5432
  encoding: utf8
  username: cook_book_api
  password: <%= ENV["POSTGRES_PASSWORD"] %>
